module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    theme: {
        extend: {
            spacing: {
                '1vh': '1vh',
                '2vh': '2vh',
                '3vh': '3vh',
                '4vh': '4vh',
                '5vh': '5vh',
                '6vh': '6vh',
                '7vh': '7vh',
                '8vh': '8vh',
                '9vh': '9vh',
                '10vh': '10vh',
                '20vh': '20vh',
                '30vh': '30vh',
                '40vh': '40vh',
                '50vh': '50vh',
                '60vh': '60vh',
                '70vh': '70vh',
                '80vh': '80vh',
                '90vh': '90vh',
                '91vh': '91vh',
                '92vh': '92vh',
                '100vh': '100vh',
            },
        },
    },
    plugins: [],
};
